<template>
  <div class="nav_component d-flex flex-column slide-in-left">
    <ul class="nav nav-pills flex-column mb-auto">
      <!-- <li>
        <router-link to="/home" class="nav_link text-white">
          <i class="fas fa-home"></i> Home
        </router-link>
      </li> -->
      <li>
        <router-link to="/newboard/notice" class="nav_link text-black">
          <i class="fas fa-bell"></i> 공지사항</router-link
        >
      </li>
      <li>
        <router-link
          to="/newboard/vaccine"
          class="nav_link text-black"
          v-on:click="closeMenu"
          ><i class="fas fa-syringe"></i> 백신</router-link
        >
      </li>
      <li>
        <router-link
          to="/newboard/elecar"
          class="nav_link text-black"
          v-on:click="closeMenu"
          ><i class="fas fa-level-up-alt"></i> 고소차</router-link
        >
      </li>
      <li>
        <router-link to="crane" class="nav_link text-black"
          ><i class="fas fa-cubes"></i> 크레인</router-link
        >
      </li>
      <li>
        <router-link to="welding" class="nav_link text-black">
          <i class="fas fa-bolt"></i> 용접기</router-link
        >
      </li>
      <li>
        <a href="#" v-on:click="logout" class="nav_link text-black">로그아웃</a>
      </li>
    </ul>
    <div v-if="admin == 1">
      <router-link to="/userManage" class="nav_link text-black">
        <i class="fas fa-cog"></i> 회원 관리</router-link
      >
    </div>
  </div>

  <div class="close-button slide-in-left" v-on:click="closeMenu">
    <i class="fas fa-times"></i>
  </div>
</template>

<script>
import { useStore } from 'vuex';

export default {
  data() {
    return {
      store: useStore(),
      admin: localStorage.getItem('admin'),
    };
  },
  methods: {
    logout: async function () {
      let setcookie = async () => {
        document.cookie =
          'auth=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;';
      };
      await setcookie();
      localStorage.setItem('department', '');
      localStorage.setItem('admin', '');
      this.store.commit('setToken', '');
    },
    closeMenu: function () {
      this.store.commit('setMenu', false);
    },
  },
  watch: {
    $route: {
      handler(val) {
        console.log(val.path);
      },
      immediate: true,
    },
  },
};
</script>
<style scoped>
.nav-title > h1 {
  font-size: 18px;
  font-weight: lighter;
}

.nav_component {
  z-index: 1000;
  position: fixed;
  left: 0;
  right: 0;
  background: #ffffff;
  top: 96px;
  width: 248px;
  height: calc(100vh - 96px);
  box-shadow: 0 2.7px 9px rgb(0 0 0 / 13%), 0 9.4px 24px rgb(0 0 0 / 9%),
    0 21.8px 43px rgb(0 0 0 / 8%);
}

.close-button {
  z-index: 1000;
  position: fixed;
  left: 266px;
  color: #eeeeee;
  background: #69707d;
  top: 112px;
  font-size: 24px;
  width: 32px;
  height: 32px;
  display: flex;
  align-items: center;
  border-radius: 5px;
  cursor: pointer;
}

.close-button > i {
  margin: 0 auto;
}

.nav_component > ul {
  list-style: none;
  padding-left: 0px;
}

.nav_component > ul > li {
  padding: 10px 5px 10px 5px;
}

.nav_component > ul > li > a {
  text-decoration: none;
  background: 0 0;
  border: 0;
  border-radius: 0.25rem;
  animation-fill-mode: forwards;
}

.nav_link {
  display: block;
  padding: 0.5rem 1rem;
  text-decoration: none;
  transition: color 0.15s ease-in-out, background-color 0.15s ease-in-out,
    border-color 0.15s ease-in-out;
}

.nav_component > ul > li > a:hover {
  background-color: #eeeeee !important;
}

.nav a.router-link-active {
  background-color: #eeeeee !important;
}

.slide-in-left {
  -webkit-animation: slide-in-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    both;
  animation: slide-in-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-2-11 14:31:24
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-left
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
    transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
    transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
</style>
